DROP TABLE SKD;
CREATE TABLE SKD(
	Name VARCHAR(50) primary key,
	YearStarted INTEGER,
	YearEnded INTEGER,
	ProvenVictims INTEGER,
	PossibleVictims VARCHAR(10),
	StatusOrLocation VARCHAR(150),
	Notes VARCHAR(500)
);

INSERT INTO SKD VALUES ('Ables, Tony', 1970, 1990, 4, '4+', 'Sentenced to death; commuted to life imprisonment.', 'Murdered robbery victim in 1970, and at least three women until 1990 in St. Petersburg, Florida');
INSERT INTO SKD VALUES ('Ackroyd, John Arthur', 1976, 1992, 1, '3+', 'Died in prison', 'Suspected in multiple murders along Oregons Highway 20');
INSERT INTO SKD VALUES ('Adams, Edward J.', 1920, 1921, 7, '7', 'Killed by police during shootout', 'Criminal who murdered seven people, including three policemen');
INSERT INTO SKD VALUES ('Alcala, Rodney', 1971, 1979, 8, '50–130', 'Sentenced to death', 'Sometimes called the "Dating Game Killer" because of his 1978 appearance on the television show The Dating Game in the midst of his murder spree');
INSERT INTO SKD VALUES ('Allen, Howard', 1974, 1987, 3, '3', 'Incarcerated for 60 years', 'Preyed on the elderly in Indiana. Death sentence commuted');
INSERT INTO SKD VALUES ('Allen, Quincy', 2002, 2003, 4, '4', 'Sentenced to death', 'Murdered four people in North and South Carolina between July–August 2002');
INSERT INTO SKD VALUES ('Angelo, Richard', 1987, 1988, 4, '10', 'Sentenced to 50 years to life in prison', 'Long Island nurse who poisoned patients in his care.');
INSERT INTO SKD VALUES ('Archerd, William Dale', 1947, 1966, 3, '6', 'Died in prison', 'First person convicted of using insulin as a murder weapon');
INSERT INTO SKD VALUES ('Archer-Gilligan, Amy', 1910, 1917, 10, '50', 'Died in Connecticut Hospital for the Insane', 'Poisoned a husband and residents of her nursing home');
INSERT INTO SKD VALUES ('Armstrong, John Eric', 1992, 1999, 5, '18', 'Sentenced to life imprisonment', 'Navy sailor convicted for murdering prostitutes in Michigan and Illinois; confessed to more murders around the world');
INSERT INTO SKD VALUES ('Atkins, Benjamin', 1991, 1992, 11, '11', 'Died in prison', 'Also known as the "Woodward Corridor Killer"; operated in Detroit.');
INSERT INTO SKD VALUES ('Avila-Torrez, Jorge', 2005, 2009, 3, '3', 'Sentenced to death', 'Murdered two underage girls in 2005');
INSERT INTO SKD VALUES ('Balaam, Anthony', 1994, 1996, 4, '4', 'Sentenced to life imprisonment', 'Known as the "Trenton Strangler"; raped and murdered four women in Trenton, New Jersey');
INSERT INTO SKD VALUES ('Ball, Joe', 1936, 1938, 2, '20', 'Committed suicide to avoid apprehension', 'Known as the "Alligator Man"');
INSERT INTO SKD VALUES ('Barber, Danny', 1977, 1979, 4, '4', 'Executed 1999', 'Murdered four people in Dallas County, Texas between 1977 and 1979');
INSERT INTO SKD VALUES ('Barfield, Velma', 1971, 1978, 1, '6', 'Executed 1984', 'Barfield was the first woman in the United States to be executed after the 1976 resumption of capital punishment and the first since 1962. She was also the first woman to be executed by lethal injection.');
INSERT INTO SKD VALUES ('Barnabet, Clementine', 1911, 1912, 35, '35', 'Escaped from prison', 'An axe murdering voodoo priestess who murdered African-American families at nighttime.');
INSERT INTO SKD VALUES ('Barone, Cesar', 1991, 1993, 4, '4+', 'Died in prison before execution', 'Killed four women around the Portland area');
INSERT INTO SKD VALUES ('Baumeister, Herb', 1980, 1996, 11, '20', 'Committed suicide while a fugitive', 'Responsible for murdering at least 11 victims who were found buried on his property in Westfield, Indiana');
INSERT INTO SKD VALUES ('Baxter, Patrick', 1987, 1990, 3, '3', 'Sentenced to life imprisonment', 'Raped and murdered one girl and two women in Westchester County, New York');
INSERT INTO SKD VALUES ('Beck, Martha', 1947, 1949, 3, '20', 'Executed 1951', 'Along with accomplice Raymond Fernandez, became known as the "Lonely Hearts Killers"');
INSERT INTO SKD VALUES ('Bender Family', 1869, 1872, 11, '11+', 'Unknown', 'Family of serial killers who lived and operated in Labette County, Kansas');
INSERT INTO SKD VALUES ('Berdella, Robert', 1984, 1987, 6, '6', 'Died in prison', 'Known as the "Kansas City Butcher" and "The Collector"');
INSERT INTO SKD VALUES ('Berkowitz, David', 1976, 1977, 6, '6', 'Sentenced to life imprisonment', 'Also known as the "Son of Sam"');
INSERT INTO SKD VALUES ('Bianchi, Kenneth', 1977, 1978, 12, '12', 'Sentenced to life imprisonment', 'Along with accomplice Angelo Buono Jr., known as the "Hillside Stranglers". Murdered young women in Los Angeles and Washington');
INSERT INTO SKD VALUES ('Biegenwald, Richard', 1958, 1983, 6, '11', 'Died in prison', 'Active in New Jersey, suspected in at least two other murders');
INSERT INTO SKD VALUES ('Bird, Jake', 1930, 1947, 2, '46', 'Executed 1949', 'Sentenced to death for the murders of two people; confessed to 44 other murders');
INSERT INTO SKD VALUES ('Bishop, Arthur Gary', 1979, 1983, 5, '5', 'Executed 1988', 'Preyed on young boys in Utah between 1979 and 1983');
INSERT INTO SKD VALUES ('Bittaker, Lawrence', 1979, 1980, 5, '5', 'Died in prison awaiting execution', 'With accomplice Roy Norris known as the "Tool Box Killers"');
INSERT INTO SKD VALUES ('Bittrolff, John', 1993, 1994, 2, '4+', 'Sentenced to 25 years to life', 'Suspect in Long Island serial killer case');
INSERT INTO SKD VALUES ('Bladel, Rudy', 1963, 1978, 3, '7', 'Died while incarcerated at Henry Ford Allegiance Health', 'Known as "The Railway Killer"; his case was part of Michigan v. Jackson, which was later overruled by the Supreme Court');
INSERT INTO SKD VALUES ('Blair, Terry', 1982, 2004, 7, '9', 'Sentenced to life imprisonment', 'Sentenced 25 years imprisonment for one murder, released on parole after serving 21 years and committed additional murders upon release');
INSERT INTO SKD VALUES ('Bolin, Oscar Ray', 1986, 1987, 4, '4+', 'Executed 2016', 'Murdered three women in Florida and a fourth woman in Texas');
INSERT INTO SKD VALUES ('Bonin, William', 1979, 1980, 21, '36+', 'Executed 1996', 'Known as the "Freeway Killer"; preyed on young men and boys in southern California with several accomplices');
INSERT INTO SKD VALUES ('Bounds, Dallen', 1999, 2000, 4, '4+', 'Committed suicide to avoid apprehension', '');
INSERT INTO SKD VALUES ('Bowles, Gary Ray', 1994, 1995, 6, '25', 'Executed 2019', 'Targeted gay men in Florida, Georgia and Maryland');
INSERT INTO SKD VALUES ('Bradford, William', 1984, 1985, 2, '28+', 'Died in prison awaiting execution', 'Suspected of more murders due to his modus operandi of taking photographs of his victims');
INSERT INTO SKD VALUES ('Brandt, Charlie', 1971, 2004, 3, '6+', 'Committed suicide to avoid apprehension', 'Shot his parents in 1971 when he was 13, killing his pregnant mother. Stabbed his wife and niece to death in 2004');
INSERT INTO SKD VALUES ('Brashers, Robert Eugene', 1990, 1998, 3, '3+', 'Committed suicide before he could be arrested', 'Known as "Mister Maroon"');
INSERT INTO SKD VALUES ('Briley Brothers', 1979, 1980, 11, '20', 'Executed 1984/1985', 'Three brothers and an accomplice responsible for 11 murders');
INSERT INTO SKD VALUES ('Brockelhurst, Lester', 1937, 1938, 3, '3+', 'Executed 1938', 'Known as "The Crime Tourist"; together with Bernice Felton, killed at least three men in holdups in three states');
INSERT INTO SKD VALUES ('Brown, Debra Denise', 1984, 1985, 8, '8', 'Sentenced to death, commuted to life imprisonment', 'Accomplice of Alton Coleman');
INSERT INTO SKD VALUES ('Brown, Kenyel', 2019, 2020, 6, '6+', 'Committed suicide to avoid apprehension', 'Known as the "Metro Detroit Serial Killer"');
INSERT INTO SKD VALUES ('Browne, Robert Charles', 1970, 1995, 2, '2+', 'Sentenced to life imprisonment', 'Missionary convicted for two murders; confessed to murdering 49 women');
INSERT INTO SKD VALUES ('Brudos, Jerry', 1968, 1969, 4, '4+', 'Died in prison', 'Known as the "Lust Killer" and "Shoe Fetish Slayer"');
INSERT INTO SKD VALUES ('Buell, Robert Anthony', 1981, 1983, 2, '3+', 'Executed 2002', '');
INSERT INTO SKD VALUES ('Buenoano, Judy', 1971, 1983, 3, '3+', 'Executed 1998', 'Caught in 1983 after poisoning and car bombing a fiancée');
INSERT INTO SKD VALUES ('Bullock, David', 1981, 1982, 6, '6+', 'Sentenced to 150 years imprisonment', 'Known as "The .38 Caliber Killer"; shot people at random around New York City to "amuse himself"');
INSERT INTO SKD VALUES ('Bunday, Thomas', 1979, 1981, 5, '6', 'Died in an intentional motorcycle crash', 'Never arrested, as he was released after interrogation on a technicality');
INSERT INTO SKD VALUES ('Bundy, Carol M.', 1980, 1981, 7, '7', 'Died in prison', 'With accomplice Doug Clark, known as the "Sunset Strip Killers""');
INSERT INTO SKD VALUES ('Bundy, Ted', 1971, 1978, 28, '30+', 'Executed 1989', '');
INSERT INTO SKD VALUES ('Buono Jr., Angelo', 1977, 1978, 9, '10', 'Died in prison', 'Along with accomplice Kenneth Bianchi, known as the "Hillside Stranglers". Murdered young women in Los Angeles');
INSERT INTO SKD VALUES ('Butler, Eugene', 1900, 1906, 6, '6', 'Died in North Dakota State Hospital', 'Crimes discovered two years after his death');
INSERT INTO SKD VALUES ('Cannon, Patty', 1802, 1829, 4, '25+', 'Died in prison awaiting trial', 'Gang leader who kidnapped slaves and free blacks to either sell or torture them');
INSERT INTO SKD VALUES ('Caputo, Ricardo', 1971, 1977, 4, '6', 'Died in prison', 'Argentine-born man who killed three women in the U.S. and one in Mexico');
INSERT INTO SKD VALUES ('Carignan, Harvey', 1949, 1974, 2, '5+', 'Incarcerated 150 years', 'Known as the "Want-Ad Killer"; escaped hanging for a 1949 killing on a technicality');
INSERT INTO SKD VALUES ('Carpenter, David', 1979, 1981, 7, '10+', 'Sentenced to death', 'Also known as the "Trailside Killer"');
INSERT INTO SKD VALUES ('Carr, Thomas D.', 1860, 1869, 1, '15', 'Executed 1870', 'First legal execution in Belmont County, Ohio');
INSERT INTO SKD VALUES ('Carson, Michael Bear', 1981, 1983, 3, '12', 'Sentenced to 75 years to life', 'Along with his wife, Suzan Carson, dubbed "The San Francisco Witch Killers"; considered suspects in nearly a dozen other deaths in the U.S. and Europe.[64]');
INSERT INTO SKD VALUES ('Carson, Suzan', 1981, 1983, 3, '12', 'Sentenced to 75 years to life', 'Along with her husband, Michael Bear Carson, dubbed "The San Francisco Witch Killers"; considered suspects in nearly a dozen other deaths in the U.S. and Europe.[64]');
INSERT INTO SKD VALUES ('Catlin, Steven David', 1976, 1984, 3, '3', 'Sentenced to death', 'Poisoned his mother and two wives with Paraquat');
INSERT INTO SKD VALUES ('Chandler, Oba', 1989, 1990, 4, '4+', 'Executed 2011', 'Murdered a three-person family and another woman in Florida; suspected of other murders since 1963');
INSERT INTO SKD VALUES ('Chase, Richard', 1977, 1978, 6, '6', 'Committed suicide awaiting execution', 'Known as the "Vampire of Sacramento"');
INSERT INTO SKD VALUES ('Christiansen, Thor Nis', 1976, 1979, 4, '4', 'Murdered in prison by unknown assailant', 'Preyed on college-aged women in California');
INSERT INTO SKD VALUES ('Christopher, Joseph', 1980, 1981, 12, '12+', 'Died in prison', 'Known as the "Midtown Slasher"');
INSERT INTO SKD VALUES ('Clark, Doug', 1980, 1981, 7, '7', 'Sentenced to death', 'With accomplice Carol M. Bundy, known as the "Sunset Strip Killers""');
INSERT INTO SKD VALUES ('Clark, Hadden', 1986, 1992, 2, '2+', 'Sentenced to 70 years', 'Cannibal convicted of two murders; confessed to killing 12');
INSERT INTO SKD VALUES ('Clark, Roland E.', 1967, 1968, 2, '9', 'Died in prison', '');
INSERT INTO SKD VALUES ('Clement, Mary', 1880, 1885, 4, '4', 'Released in 1886', 'Luxembourgish immigrant who poisoned her family members with arsenic');
INSERT INTO SKD VALUES ('Cline, Alfred Leonard', 1930, 1945, 9, '11', 'Died in prison', 'Murdered his wives with poisoned buttermilk after persuading them to will their possessions to his name.');
INSERT INTO SKD VALUES ('Coffman, Cynthia', 1986, 1987, 4, '4', 'Sentenced to death', 'Kidnapped four women by ATMs before accomplice strangled them');
INSERT INTO SKD VALUES ('Cole, Carroll', 1971, 1980, 16, '35', 'Executed 1985', 'Strangled fifteen women and one boy in California, Nevada and Texas');
INSERT INTO SKD VALUES ('Coleman, Alton', 1984, 1985, 8, '8', 'Executed 2002', 'Multi-state killer who along with his accomplice murdered a man and injured another, murdered four women and three young girls, and raped a young girl');
INSERT INTO SKD VALUES ('Colvin, Dellmus', 1987, 2005, 7, '7+', 'Sentenced to life imprisonment', 'Truck driver who killed prostitutes in New Jersey and Ohio');
INSERT INTO SKD VALUES ('Conde, Rory Enrique', 1994, 1995, 6, '6', 'Sentenced to death', 'Known as the "Tamiami Trail Strangler"');
INSERT INTO SKD VALUES ('Cook, Anthony', 1973, 1981, 9, '9+', 'Sentenced to 15 years to life imprisonment', 'Committed crimes with his brother Nathaniel Cook');
INSERT INTO SKD VALUES ('Cook, Nathaniel', 1973, 1981, 9, '9+', 'Released in 2018', 'Committed crimes with his brother Anthony Cook');
INSERT INTO SKD VALUES ('Cooks, Jessie Lee', 1973, 1974, 15, '73+', 'Sentenced to life imprisonment', 'Part of the "Death Angels" cult responsible for the Zebra murders');
INSERT INTO SKD VALUES ('Copeland, Faye', 1986, 1989, 5, '12', 'Died in prison awaiting execution', 'Along with her husband, Ray Copeland, the oldest couple ever sentenced to death in the United States');
INSERT INTO SKD VALUES ('Copeland, Ray', 1986, 1989, 5, '12', 'Died in prison awaiting execution', 'Along with his wife, Faye Copeland, the oldest couple ever sentenced to death in the United States');
INSERT INTO SKD VALUES ('Corll, Dean', 1970, 1973, 28, '28+', 'Killed by accomplice Elmer Wayne Henley', 'Crimes referred to as the "Houston Mass Murders"');
INSERT INTO SKD VALUES ('Corona, Juan', 1971, 1972, 25, '25+', 'Died in prison', 'Majority of victims had been transient workers');
INSERT INTO SKD VALUES ('Corwin, Daniel Lee', 1987, 1988, 3, '3', 'Executed 1998', 'Abducted and killed three women around Texas');
INSERT INTO SKD VALUES ('Costa, Tony', 1968, 1969, 4, '8', 'Committed suicide in prison', 'Preyed on women in and around Truro, Massachusetts');
INSERT INTO SKD VALUES ('Cottingham, Richard', 1967, 1980, 9, '85–100', 'Sentenced to life imprisonment', 'Known variously as the "Butcher of Times Square", the "Torso Killer", the "New York (City) Ripper", and the "Times Square Torso Ripper"');
INSERT INTO SKD VALUES ('Cowan, Mary', 1884, 1894, 6, '6', 'Died in prison', 'Known as "The Borgia of Maine"');
INSERT INTO SKD VALUES ('Cox, Frederick Pete', 1997, 1998, 3, '3', 'Sentenced to life imprisonment', 'Murdered prostitutes in Orlando, Florida');
INSERT INTO SKD VALUES ('Cox, Scott William', 1980, 1990, 2, '20+', 'Granted parole in 2013', '');
INSERT INTO SKD VALUES ('Craine, Louis', 1984, 1987, 4, '5+', 'Died in prison', 'Responsible for at least two of the "Southside Slayer" murders in South Los Angeles');
INSERT INTO SKD VALUES ('Crawford, Andre', 1993, 1999, 11, '11', 'Sentenced to life imprisonment', 'Chicago transient who preyed on prostitutes and the destitute');
INSERT INTO SKD VALUES ('Creighton, Mary Frances', 1920, 1935, 1, '4', 'Executed 1936', 'Poisoned her lovers wife; suspected of poisoning her mother in-law, father in-law, and younger brother');
INSERT INTO SKD VALUES ('Cullen, Charles', 1988, 2003, 10, '40+', 'Incarcerated 127 years', 'A nurse in New Jersey and Pennsylvania');
INSERT INTO SKD VALUES ('Cunanan, Andrew', 1997, 1998, 5, '5', 'Committed suicide while a fugitive', '');
INSERT INTO SKD VALUES ('Curry, James Richard', 1982, 1983, 4, '5', 'Committed suicide after being arrested', '');
INSERT INTO SKD VALUES ('Dahmer, Jeffrey', 1978, 1991, 17, '17', 'Murdered by inmate Christopher Scarver', 'Milwaukee cannibal who retained various body parts of his victims');
INSERT INTO SKD VALUES ('DeAngelo, Joseph James', 1979, 1986, 13, '13+', 'Sentenced to life in prison without possibility of parole', 'Also known as the "Golden State Killer", "Visalia Ransacker", "East Area Rapist", and the "Original Night Stalker"; murdered three people in Sacramento and 10 people in Southern California from 1975 through 1986; also linked to more than 50 rapes in the Sacramento area from 1976 to 1979. Suspect arrested on April 24, 2018. Pled guilty on June 29, 2020 to avoid the death penalty. On August 21, 2020, DeAngelo was sentenced to life in prison without possibility of parole.');
INSERT INTO SKD VALUES ('DeBardeleben, Mike', 1965, 1983, 0, '8', 'Died from pneumonia in prison', 'Also known as the "Mall Passer"; convicted rapist and counterfeiter who kidnapped, raped, and tortured numerous women. Although never convicted of murder, Debardeleben is suspected to be behind the killings of at least eight women.');
INSERT INTO SKD VALUES ('Dieteman, Samuel', 2005, 2006, 8, '8', 'Sentenced to life imprisonment', 'Accomplice Dale Hausner committed suicide in prison');
INSERT INTO SKD VALUES ('Dillon, Thomas', 1989, 1992, 5, '5+', 'Died in prison', 'Shot men at random in southeastern Ohio');
INSERT INTO SKD VALUES ('Dodd, Westley Allan', 1989, 1990, 3, '3', 'Executed 1993', 'Convicted sex offender who sexually assaulted and murdered three young boys in Vancouver, Washington in 1989');
INSERT INTO SKD VALUES ('Dominique, Ronald', 1997, 2006, 23, '23+', 'Sentenced to life imprisonment', 'Raped and murdered male victims in Louisiana');
INSERT INTO SKD VALUES ('Doss, Nannie', 1927, 1954, 8, '11', 'Died in prison', 'Known as the "Giggling Granny" and the "Jolly Black Widow"; serial poisoner killed four husbands, two children, her two sisters, her mother, a grandson, and a mother-in-law');
INSERT INTO SKD VALUES ('Dugan, Brian', 1983, 1985, 3, '3', 'Sentenced to life imprisonment', '');
INSERT INTO SKD VALUES ('Duncan III, Joseph E.', 1996, 2005, 5, '7', 'Sentenced to life imprisonment', 'Raped at least 17 young boys and three young girls');
INSERT INTO SKD VALUES ('Durousseau, Paul', 1997, 2003, 7, '7+', 'Sentenced to death (overturned on January 31, 2017; awaiting resentencing)', 'Murdered seven women in the Southeastern United States, included two who were pregnant. German authorities suspect Durousseau may have killed several local women when he was stationed there with the Army during the early 1990s.');
INSERT INTO SKD VALUES ('Eaton, Dale Wayne', 1988, 2001, 2, '11+', 'Sentenced to death (overturned – awaiting resentencing hearing)', 'Eaton is also suspected of being behind the killings known as the "Great Basin Murders". ');
INSERT INTO SKD VALUES ('Edwards, Andrew David', 1987, 1992, 4, '4', 'Sentenced to life imprisonment', 'Murdered transients in alcohol-induced rages');
INSERT INTO SKD VALUES ('Edwards, Edward', 1977, 1996, 5, '15', 'Died in prison awaiting execution', 'Sentenced to death for shooting his foster son in 1996 insurance murder');
INSERT INTO SKD VALUES ('Edwards, Mack Ray', 1953, 1970, 3, '18', 'Committed suicide awaiting execution', 'Preyed on children in Los Angeles County, California');
INSERT INTO SKD VALUES ('Ellis, Walter E.', 1986, 2007, 7, '7', 'Died in prison', 'Known as the "Milwaukee North Side Strangler"');
INSERT INTO SKD VALUES ('Erskine, Scott', 1989, 1993, 3, '3+', 'Died in prison awaiting execution', 'Raped and murdered two young boys in California and a woman in Florida');
INSERT INTO SKD VALUES ('Espinosa, Felipe', 1863, 1864, 32, '32', 'Killed by Tom Tobin', '');
INSERT INTO SKD VALUES ('Evans, Donald Leroy', 1985, 1991, 3, '70', 'Died in prison; murdered by a fellow death row inmate', 'Suspected of another dozen murders but recanted his confessions to over 70 more');
INSERT INTO SKD VALUES ('Evans, Franklin B.', 1850, 1872, 2, '5+', 'Executed 1874', 'Known as "The Northwood Murderer"; vagrant who murdered at least two young girls in New Hampshire, and possibly more in Maine and Massachusetts');
INSERT INTO SKD VALUES ('Evans, Gary', 1985, 1997, 5, '5', 'Committed suicide to avoid apprehension', '');
INSERT INTO SKD VALUES ('Evonitz, Richard', 1996, 1997, 3, '3+', 'Committed suicide to avoid apprehension', '');
INSERT INTO SKD VALUES ('Eyler, Larry', 1982, 1984, 21, '24', 'Died in prison awaiting execution', 'Known as the "Interstate Killer"');
INSERT INTO SKD VALUES ('Falling, Christine', 1980, 1982, 6, '6', 'Sentenced to life imprisonment', 'Epileptic who strangled infants because of voices in her head');
INSERT INTO SKD VALUES ('Falls, Neal', 1992, 2015, 0, '10+', 'Killed by intended victim', 'Suspected of killing up to 10 women before being killed in self defense.');
INSERT INTO SKD VALUES ('Fautenberry, John', 1990, 1991, 5, '6', 'Executed 2009', 'Befriended, murdered and robbed people across four states');
INSERT INTO SKD VALUES ('Fayne, Lorenzo', 1989, 1993, 6, '6', 'Sentenced to death; commuted to life imprisonment', 'Raped and murdered a woman and five children in Wisconsin and Illinois');
INSERT INTO SKD VALUES ('Feigenbaum, Carl', 1888, 1894, 1, '13+', 'Executed 1896', 'German sailor who murdered his landlord in 1894; allegedly responsible for murders in other countries, also suspect in the Jack the Ripper case.');
INSERT INTO SKD VALUES ('Fernandez, Raymond', 1947, 1949, 3, '20', 'Executed 1951', 'Along with accomplice Martha Beck, became known as the "Lonely Hearts Killers"');
INSERT INTO SKD VALUES ('Fish, Albert', 1924, 1932, 3, '8+', 'Executed 1936', 'Also known as the "Werewolf of Wysteria"; sadist and pedophile who cannibalized several children.');
INSERT INTO SKD VALUES ('Fisher, Lavinia', 9999, 1819, 0, 'Numerous', 'Executed 1820', 'Along with her husband John was a member of a highway gang; allegedly killed travelers visiting her inn.');
INSERT INTO SKD VALUES ('Ford, Wayne Adam', 1997, 1998, 4, '4+', 'Sentenced to death', 'Killed and mutilated four women in California');
INSERT INTO SKD VALUES ('Fowler, Bobby Jack', 1973, 1996, 1, '20', 'Died in prison', 'Convicted of one murder, suspected of up to 20 more.');
INSERT INTO SKD VALUES ('Francois, Kendall', 1996, 1998, 8, '10+', 'Died in prison', 'Known as the "Poughkeepsie Killer"');
INSERT INTO SKD VALUES ('Franklin, Joseph Paul', 1977, 1980, 11, '22', 'Executed 2013', 'Also attempted to assassinate Larry Flynt and Vernon Jordan');
INSERT INTO SKD VALUES ('Franklin Jr., Lonnie David', 1985, 2007, 10, '25+', 'Died in prison', 'Known as "Grim Sleeper"; charged after DNA evidence linked him with ten murders in Los Angeles since 1985');
INSERT INTO SKD VALUES ('Gacy, John Wayne', 1972, 1978, 33, '33+', 'Executed 1994', 'Known as the "Killer Clown"');
INSERT INTO SKD VALUES ('Gallego, Gerald', 1978, 1980, 10, '10', 'Died awaiting execution', 'Accomplice Charlene Gallego released 1997');
INSERT INTO SKD VALUES ('Gargiulo, Michael', 1993, 2008, 3, '10', 'Awaiting capital murder trial', 'Known as the "Hollywood Ripper""');
INSERT INTO SKD VALUES ('Gary, Carlton', 1970, 1978, 7, '7+', 'Executed 2018', 'Known as the "Stocking Strangler"');
INSERT INTO SKD VALUES ('Gaskins, Donald Henry', 1953, 1982, 9, '100+', 'Executed 1991', 'Convicted of nine murders; claimed to an author to have killed more than 100');
INSERT INTO SKD VALUES ('Gaynor, Alfred', 1995, 1998, 9, '9', 'Sentenced to life imprisonment', 'Raped and strangled drug-addicted women in Springfield, Massachusetts');
INSERT INTO SKD VALUES ('Gecht, Robin', 1981, 1982, 18, '18', 'Incarcerated for 120 years', 'Member of the satanic cult and organized crime group known as Ripper Crew or Chicago Rippers');
INSERT INTO SKD VALUES ('Gein, Ed', 1954, 1957, 2, '7', 'Died while incarcerated at Mendota Mental Health Institute', 'Known as the "Plainfield Ghoul". Geins life and crimes have inspired, at least in part, the novels/films, Psycho and The Silence of the Lambs, and the 1974 movie, The Texas Chain Saw Massacre.');
INSERT INTO SKD VALUES ('Geralds, Hubert', 1994, 1995, 5, '5', 'Sentenced to death; commuted to life imprisonment', 'Known as the "Englewood Strangler"');
INSERT INTO SKD VALUES ('Gibbs, Janie Lou', 1966, 1967, 5, '5', 'Died in prison', 'Killed her three sons, a grandson, and her husband, by arsenic poisoning');
INSERT INTO SKD VALUES ('Gibson, Mose', 1908, 1920, 3, '7+', 'Executed 1920', 'Guilt has been questioned');
INSERT INTO SKD VALUES ('Gibson, William Clyde', 2002, 2012, 3, '3+', 'Sentenced to death', '');
INSERT INTO SKD VALUES ('Gifford, Bertha', 1900, 1928, 3, '17', 'Died in Missouri State Hospital #4', 'Found not guilty by reason of insanity');
INSERT INTO SKD VALUES ('Gilbert, Kristen', 1989, 1996, 4, '4', 'Sentenced to life imprisonment', 'Induced cardiac arrest in patients and would then respond to the coded emergency, often resuscitating the patients herself');
INSERT INTO SKD VALUES ('Giles, Bernard', 1973, 1974, 5, '5', 'Sentenced to life imprisonment', 'Abducted, raped and murdered female hitchhikers in orange groves near Titusville, Florida');
INSERT INTO SKD VALUES ('Gillis, Sean Vincent', 1994, 2004, 8, '8', 'Sentenced to life imprisonment', 'Stalked, kidnapped, raped, murdered, and mutilated Louisiana women');
INSERT INTO SKD VALUES ('Gilyard, Lorenzo', 1977, 1993, 12, '13', 'Sentenced to life imprisonment', 'Known as the "Kansas City Strangler"');
INSERT INTO SKD VALUES ('Glatman, Harvey', 1957, 1958, 3, '4', 'Executed 1959', 'Known as the "Lonely Hearts Killer"; lured women to pose for "bondage photographs"');
INSERT INTO SKD VALUES ('Glaze, Billy', 1986, 1987, 3, '20+', 'Died in prison', 'Guilt has come into question by the discovery of DNA evidence excluding Glaze and implicating another man');
INSERT INTO SKD VALUES ('Gohl, Billy', 1902, 1910, 2, '100+', 'Died in prison', 'Union official linked with the disappearances of over 40 sailors in Aberdeen, Washington in the early 20th century');
INSERT INTO SKD VALUES ('Gore, David Alan', 1981, 1983, 6, '6', 'Executed 2012', 'One of the pair known as the "Killing Cousins"');
INSERT INTO SKD VALUES ('Goudeau, Mark', 2005, 2006, 9, '9', 'Sentenced to death', 'Known as the "Baseline Killer"');
INSERT INTO SKD VALUES ('Graham, Gwendolyn', 1987, 1988, 5, '6', 'Sentenced to life imprisonment', 'Accomplice of Cathy Wood');
INSERT INTO SKD VALUES ('Graham, Harrison', 1986, 1987, 7, '7', 'Sentenced to life imprisonment', 'Murdered seven women in Philadelphia');
INSERT INTO SKD VALUES ('Grate, Shawn', 2006, 2016, 5, '5', 'Sentenced to death', 'Murdered women in rural Ohio');
INSERT INTO SKD VALUES ('Gray, Dana Sue', 1994, 1995, 3, '3', 'Sentenced to life imprisonment', 'Preyed on elderly women, murdering three; caught after a fourth intended victim survived and identified her');
INSERT INTO SKD VALUES ('Gray, Marvin', 1971, 1992, 3, '41', 'Died in prison', 'Most dangerous prisoner in Colorado until his death; confessed to the murders of 41 people across eight different states');
INSERT INTO SKD VALUES ('Gray, Ronald', 1986, 1987, 4, '4', 'Sentenced to death', '');
INSERT INTO SKD VALUES ('Green, Larry', 1973, 1974, 15, '73+', 'Sentenced to life imprisonment', 'Part of the "Death Angels" cult responsible for the Zebra murders');
INSERT INTO SKD VALUES ('Green, Ricky Lee', 1985, 1986, 4, '12', 'Executed 1997', 'Bisexual drifter; his wife helped in two of the murders');
INSERT INTO SKD VALUES ('Green, Samuel', 1817, 1821, 2, '2+', 'Executed 1822', 'Known as the "Terror of New England"');
INSERT INTO SKD VALUES ('Greenwood, Vaughn', 1964, 1975, 11, '11', 'Sentenced to life imprisonment', 'Known as the "Skid Row Slasher"');
INSERT INTO SKD VALUES ('Groves, Vincent', 1978, 1988, 7, '20+', 'Died in prison', 'Raped and strangled prostitutes in Denver and the surrounding areas');
INSERT INTO SKD VALUES ('Gunness, Belle', 1900, 1908, 25, '40', 'Unknown', 'Norwegian-born murder-for-profit killer who killed her suitors and children');
INSERT INTO SKD VALUES ('Hahn, Anna Marie', 1933, 1937, 5, '5', 'Executed 1938', 'German-born murder-for-profit killer who poisoned five elderly men');
INSERT INTO SKD VALUES ('Halbower, Rodney', 1976, 1977, 2, '5', 'Sentenced to life imprisonment', 'Suspect in the Gypsy Hill killings');
INSERT INTO SKD VALUES ('Halliday, Lizzie', 1890, 1900, 4, '7', 'Died in Matteawan State Hospital for the Criminally Insane', 'First woman sentenced to be executed by the electric chair');
INSERT INTO SKD VALUES ('Hance, William Henry', 1977, 1978, 4, '4', 'Executed 1994', 'Known as the "Forces of Evil"');
INSERT INTO SKD VALUES ('Hansen, Robert', 1971, 1983, 17, '21+', 'Died in prison', 'Known as the "Butcher Baker"');
INSERT INTO SKD VALUES ('Harpe Brothers', 1797, 1804, 39, '50+', 'Murdered/executed', 'Brothers or cousins; Americas first known serial killers');
INSERT INTO SKD VALUES ('Harris, DeWayne Lee', 1997, 1998, 3, '3', 'Sentenced to 94 years imprisonment', 'Known as "The Seattle Jungle Killer"; strangled prostitutes in Seattle, dumping their bodies in an area known as The Jungle');
INSERT INTO SKD VALUES ('Harvey, Donald', 1970, 1987, 37, '80', 'Died in prison, killed by inmate James Elliott', 'Known as the "Angel of Death"');
INSERT INTO SKD VALUES ('Hatcher, Charles Ray', 1969, 1982, 2, '16', 'Committed suicide in prison', 'Convicted of two child murders in 1978 and 1982, also stabbed to death a fellow inmate and another man 20 years apart');
INSERT INTO SKD VALUES ('Hausner, Dale', 2006, 2007, 8, '8', 'Committed suicide in prison', 'Convicted of killing people in random drive-by shootings');
INSERT INTO SKD VALUES ('Hayward, Harry T.', 1894, 1895, 1, '4', 'Executed 1895', 'Known as the "Minneapolis Svengali"');
INSERT INTO SKD VALUES ('Hazzard, Linda', 1908, 1911, 1, '13', 'Died in 1938', 'Served two years');
INSERT INTO SKD VALUES ('Heirens, William', 1945, 1946, 3, '3', 'Died in prison', 'Known as the "Lipstick Killer"; Illinois teenager convicted of the murder of three Chicago women in the 1940s');
INSERT INTO SKD VALUES ('Helm, Boone', 1850, 1864, 11, '11+', 'Executed 1864', 'Known as the "Kentucky Cannibal"');
INSERT INTO SKD VALUES ('Henley, Elmer Wayne', 1970, 1973, 6, '6', 'Sentenced to life imprisonment', 'Crimes referred to as the "Houston Mass Murders"');
INSERT INTO SKD VALUES ('Hermann, Francis', 1890, 1896, 2, '8', 'Unknown', 'Known as the "Priestly Butcher"; English-born pastor who murdered female church-goers, ex-wives and two of his children');
INSERT INTO SKD VALUES ('Herzog, Loren', 1984, 1999, 3, '19', 'Committed suicide awaiting parole release', 'Along with accompliace Wesley Shermantine known as the "Speed Freak Killers"');
INSERT INTO SKD VALUES ('Hickey, J. Frank', 1883, 1911, 3, '3', 'Died in prison', 'Known as the "Postcard Killer"');
INSERT INTO SKD VALUES ('Hill, Ivan', 1979, 1994, 9, '9+', 'Sentenced to death', 'Known as the "60 Freeway Killer"; responsible for at least one of the "Southside Slayer" murders');
INSERT INTO SKD VALUES ('Hilley, Audrey Marie', 1975, 1980, 1, '4', 'Died in prison', 'Poisoned her husband; suspected of poisoning her mother, mother-in-law and a child she was looking after');
INSERT INTO SKD VALUES ('Hoch, Johann Otto', 1890, 1905, 1, '50+', 'Executed 1906', 'Known as the "Stockyard Bluebeard"');
INSERT INTO SKD VALUES ('Hohenberger, Robert', 1978, 1979, 0, '5', 'Committed suicide to avoid apprehension', 'Former California police deputy linked to the kidnap-murders of teenagers in Morgan City, Louisiana');
INSERT INTO SKD VALUES ('Holmes, H. H.', 1891, 1894, 9, '27+', 'Executed 1896', 'Convicted of only one murder, but definitively tied to at least eight more; confessed to a total of 27');
INSERT INTO SKD VALUES ('Howell, William Devin', 2003, 2004, 7, '7', 'Sentenced to life imprisonment', 'Convicted of killing seven people in 2003; believed to be the most prolific serial killer in Connecticut history');
INSERT INTO SKD VALUES ('Hoyt, Waneta', 1965, 1971, 5, '5', 'Died in prison', 'Exonerated under New York law because she died before her appeal');
INSERT INTO SKD VALUES ('Hughes, Michael', 1986, 1993, 7, '7+', 'Sentenced to death', 'Known as the "Southside Slayer"');
INSERT INTO SKD VALUES ('Hunter, Richard Louis', 1986, 1987, 4, '4', 'Sentenced to life imprisonment', 'Raped and strangled elderly women in Atlanta');
INSERT INTO SKD VALUES ('Irvin, Leslie', 1954, 1955, 6, '6+', 'Died in prison', 'His Supreme Court case set a precedent for fair trials of highly publicized defendants');
INSERT INTO SKD VALUES ('Jablonski, Phillip Carl', 1978, 1991, 5, '5', 'Died in prison awaiting execution', 'Murdered women in California and Utah');
INSERT INTO SKD VALUES ('Jackson, Calvin', 1973, 1974, 9, '9', 'Sentenced to life imprisonment', 'Murdered and robbed women in Manhattans East Side, abusing their corpses post-mortem');
INSERT INTO SKD VALUES ('Jackson, Charles', 1975, 1982, 8, '8+', 'Died in prison', 'Known as the "East Bay Slayer"');
INSERT INTO SKD VALUES ('Jesperson, Keith Hunter', 1990, 1995, 8, '8+', 'Sentenced to life imprisonment', 'Known as the "Happy Face Killer"');
INSERT INTO SKD VALUES ('Johnson, John', 1843, 9999, 0, '300+', 'Died 1900', 'Known as "Liver-Eating Johnson"; mountain man who allegedly ate the livers of Crows hed slain');
INSERT INTO SKD VALUES ('Johnson, Martha Ann', 1977, 1982, 3, '4', 'Sentenced to death; commuted to life', 'Georgia woman convicted of smothering to death three of her children between 1977 and 1982');
INSERT INTO SKD VALUES ('Johnson, Matthew Steven', 2000, 2001, 3, '5', 'Sentenced to life imprisonment', 'Preyed on disenfranchised young women in Connecticut');
INSERT INTO SKD VALUES ('Johnson, Milton', 1983, 1984, 10, '10+', 'Sentenced to death, commuted to life imprisonment', 'Victims included two deputy sheriffs');
INSERT INTO SKD VALUES ('Johnson, Vincent', 1999, 2000, 5, '5', 'Sentenced to life imprisonment', 'Known as the "Brooklyn Strangler"');
INSERT INTO SKD VALUES ('Jones, Genene', 1977, 1982, 2, '60+', 'Sentenced to 99 years in prison', 'Texas pediatric nurse who poisoned infants in her care; was due to be released March 2018; however, prosecutors charged her with two additional murders');
INSERT INTO SKD VALUES ('Jones, Jack Harold', 1983, 1995, 3, '3+', 'Executed 2017', 'Murdered at least three women in Florida and Arkansas; a serial rapist was wrongfully convicted for one murder');
INSERT INTO SKD VALUES ('Jones, Syd', 1900, 1914, 13, '13', 'Executed 1915', '');
INSERT INTO SKD VALUES ('Joubert, John', 1982, 1983, 3, '3', 'Executed 1996', 'Known as the "Nebraska Boy Snatcher"');
INSERT INTO SKD VALUES ('Junco, Francisco del', 1995, 1996, 4, '4', 'Sentenced to life imprisonment', 'Cuban immigrant who murdered and then burned the bodies of prostitutes in Miami');
INSERT INTO SKD VALUES ('Kadamovas, Jurijus', 2001, 2002, 5, '5', 'Sentenced to death', 'Murdered five people in California with accomplice Iouri Mikhel.');
INSERT INTO SKD VALUES ('Kallinger, Joseph', 1974, 1975, 3, '3', 'Died in prison', 'Committed these crimes with his 15-year-old son Michael');
INSERT INTO SKD VALUES ('Kearney, Patrick', 1965, 1977, 21, '43', 'Sentenced to life imprisonment', 'Known as the "Trash Bag Killer"');
INSERT INTO SKD VALUES ('Keith, Leroy', 1934, 1956, 3, '3', 'Executed 1959', 'Shot three men during holdups in Ohio and New York');
INSERT INTO SKD VALUES ('Kelley, John William', 1986, 1988, 3, '3', 'Sentenced to life imprisonment', 'Convicted rapist who killed a young hitchhiker and a married couple in rural California');
INSERT INTO SKD VALUES ('Kelly Family', 1887, 1888, 11, '12', 'Killed by vigilantes', 'Family of serial killers who killed and robbed wealthy travellers in No Mans Land');
INSERT INTO SKD VALUES ('Kemper, Edmund', 1964, 1973, 10, '10', 'Sentenced to life imprisonment', 'Known as the "Co-Ed Killer"');
INSERT INTO SKD VALUES ('Keyes, Israel', 1990, 2012, 3, '11+', 'Committed suicide while in custody', 'Three confirmed victims; linked to 11 victims in four states');
INSERT INTO SKD VALUES ('Kibbe, Roger', 1977, 1987, 7, '7', 'Sentenced to life imprisonment', 'Known as the "I-5 Strangler"');
INSERT INTO SKD VALUES ('Kimball, Scott Lee', 2003, 2004, 4, '5+', '70-year sentence', 'FBI Informant; proposed as a suspect in the West Mesa murders');
INSERT INTO SKD VALUES ('Kimes, Sante', 1996, 1998, 2, '3', 'Died in prison', 'Criminal whos responsible for numerous crimes committed with her son, Kenneth Jr.');
INSERT INTO SKD VALUES ('Kinne, Sharon', 1962, 1964, 3, '3', 'Escaped from prison 1969', 'Her arrest warrant is one the longest outstanding in American history');
INSERT INTO SKD VALUES ('Kirkland, Anthony', 1987, 2009, 5, '6', 'Sentenced to death', 'Preyed on young women in the Cincinnati area');
INSERT INTO SKD VALUES ('Klimek, Tillie', 1914, 1921, 5, '7', 'Died in prison', 'Polish-born Chicago poisoner');
INSERT INTO SKD VALUES ('Knapp, Alfred', 1894, 1902, 5, '5+', 'Executed 1904', 'Known as the "Hamilton Strangler"');
INSERT INTO SKD VALUES ('Knight, Thomas', 1974, 1980, 4, '4', 'Executed 2014', 'Murdered four people between 1974 and 1980');
INSERT INTO SKD VALUES ('Knorr, Theresa', 1984, 1985, 2, '3', 'Sentenced to two life sentences', 'Her sons, William and Robert Jr., were accomplices');
INSERT INTO SKD VALUES ('Knotek, Michelle', 1994, 2003, 2, '3', '22 years in prison', 'Tortured and abused boarders in her home with her husband');
INSERT INTO SKD VALUES ('Knowles, Paul John', 1974, 1975, 18, '35', 'Killed by police attempting to escape from custody', 'Known as the "Casanova Killer"');
INSERT INTO SKD VALUES ('Kohlhepp, Todd', 2003, 2016, 7, '7', 'Sentenced to life imprisonment', '');
INSERT INTO SKD VALUES ('Kokoraleis, Andrew', 1981, 1982, 18, '18', 'Executed 1999', 'Member of the satanic cult and organized crime group known as "The Ripper Crew" or "The Chicago Rippers"');
INSERT INTO SKD VALUES ('Kokoraleis, Thomas', 1981, 1982, 18, '18', 'Released March 29, 2019', 'Member of the satanic cult and organized crime group known as "The Ripper Crew" or "The Chicago Rippers"');
INSERT INTO SKD VALUES ('Kondro, Joseph', 1985, 1996, 2, '3+', 'Died in prison', 'Known as "The Longview Serial Killer"; kidnapped, sexually assaulted and murdered underage girls across Washington State');
INSERT INTO SKD VALUES ('Kraft, Randy', 1971, 1983, 16, '67', 'Sentenced to death', 'Known as the "Scorecard Killer" and the "Freeway Killer"');
INSERT INTO SKD VALUES ('Krajcir, Timothy', 1977, 1982, 9, '9', 'Sentenced to life imprisonment', 'Confessed to killing five women in Missouri and four others in Illinois and Pennsylvania');
INSERT INTO SKD VALUES ('Kudzinowski, Peter', 1924, 1928, 3, '3', 'Executed 1929', 'Imprisoned for the murder of a friend. Murdered two children following his release.');
INSERT INTO SKD VALUES ('Kuklinski, Richard', 1948, 1986, 5, '100–150', 'Died in prison', 'Mafia associate known as "The Iceman"');
INSERT INTO SKD VALUES ('Kunnecke, William', 1898, 1903, 1, '3', 'Unknown', 'Escaped from prison in 1919');
INSERT INTO SKD VALUES ('LaBarre, Sheila', 2004, 2006, 2, '4', 'Sentenced to life imprisonment without parole', 'Claimed she was an angel sent by God to punish pedophiles');
INSERT INTO SKD VALUES ('Lake, Leonard', 1983, 1985, 11, '25', 'Committed suicide while in custody', 'Along with accomplice Charles Ng, they are also known as the "Operation Miranda Killers"');
INSERT INTO SKD VALUES ('LaLaurie, Delphine', 1834, 1835, 0, '?', 'Died in Paris, France', 'Tortured and maimed her slaves');
INSERT INTO SKD VALUES ('Lane, Adam Leroy', 2007, 2008, 2, '2+', 'Sentenced to 50 years', 'Known as the "Highway Killer"');
INSERT INTO SKD VALUES ('Lassor, Raymond', 1984, 1985, 3, '3', 'Sentenced to life imprisonment', 'First criminal to be successfully prosecuted under the 1984 Rhode Island Life Without Parole Statute');
INSERT INTO SKD VALUES ('Laudenberg, Adolph', 1972, 1975, 4, '6', 'Sentenced to life imprisonment', 'Known as the "Santa Strangler"');
INSERT INTO SKD VALUES ('Lee, Derrick Todd', 1992, 2003, 7, '7+', 'Died in prison awaiting execution', 'Known as the "Baton Rouge Serial Killer"; convicted of two murders; linked by DNA evidence to five others');
INSERT INTO SKD VALUES ('Legg, Samuel', 1990, 1992, 5, '5+', 'Found not guilty by reason of insanity and committed for life to Twin Valley Behavioral Health Center', 'Suspect in some of the Dr. No murders');
INSERT INTO SKD VALUES ('Lewingdon, Gary', 1977, 1978, 10, '10', 'Died in prison', 'Together with brother Thaddeus Lewingdon, known as the ".22 Caliber Killers"');
INSERT INTO SKD VALUES ('Lewingdon, Thaddeus', 1977, 1978, 9, '9', 'Died in prison', 'Together with brother Gary Lewingdon, known as the ".22 Caliber Killers"');
INSERT INTO SKD VALUES ('Lindahl, Bruce', 1974, 1981, 2, '12+', 'Died from accidental self-inflicted injuries', 'Posthumously connected to various rape-murders in Chicago and surrounding area');
INSERT INTO SKD VALUES ('Little, Jerry', 1985, 1988, 4, '4', 'Uncertain', 'Raped and strangled women in St. Louis, Missouri');
INSERT INTO SKD VALUES ('Little, Samuel', 1970, 2005, 61, '93+', 'Sentenced to life imprisonment', 'Transient who allegedly killed 93 women in 14 states; also known as the "choke-and-stroke killer"');
INSERT INTO SKD VALUES ('Lockett, Will', 1912, 1920, 4, '4', 'Executed 1920', 'Guilt has been questioned');
INSERT INTO SKD VALUES ('Lockhart, Michael Lee', 1987, 1988, 4, '6+', 'Executed 1997', 'Received death sentences in three states; executed by the state of Texas');
INSERT INTO SKD VALUES ('Long, Bobby Joe', 1984, 1985, 10, '10+', 'Executed 2019', 'Also known as the "Classified Ad Rapist"');
INSERT INTO SKD VALUES ('Longley, Bill', 1869, 1878, 32, '32', 'Executed 1878', 'Gunfighter who killed unarmed slaves and Mexicans');
INSERT INTO SKD VALUES ('Lucas, Henry Lee', 1960, 1983, 3, '200+', 'Died in prison', 'Convicted of 11 murders, confessed to approximately 3,000 murders, although most of his confessions are considered outlandish.');
INSERT INTO SKD VALUES ('Madison, Michael', 2012, 2013, 3, '3', 'Sentenced to death', 'Preyed on women in East Cleveland, Ohio');
INSERT INTO SKD VALUES ('Majors, Orville Lynn', 1993, 1995, 6, '130', 'Died in prison', 'Licensed practical nurse who was convicted of murdering his patients in Clinton, Indiana');
INSERT INTO SKD VALUES ('Malvo, Lee Boyd', 2002, 2003, 7, '17', 'Life imprisonment without parole (overturned on May 26, 2017; Supreme Court of the United States heard the case on October 16, 2019.[288]', 'With accomplice John Allen Muhammad, perpetrated the D.C. sniper attacks');
INSERT INTO SKD VALUES ('Mansfield, Billy', 1975, 1980, 5, '5', 'Sentenced to life imprisonment', 'Murdered women and girls in Florida and California, burying most of them in the family home in Weeki Wachee');
INSERT INTO SKD VALUES ('Marquette, Richard Laurence', 1956, 1975, 3, '3', 'Sentenced to life imprisonment', 'First 11th person named on the FBIs 10 Most Wanted List');
INSERT INTO SKD VALUES ('Martin, James David', 1989, 2005, 3, '3', '66 years imprisonment', 'Strangled three across three states, including his wife');
INSERT INTO SKD VALUES ('Martin, Lee Roy', 1967, 1968, 4, '4', 'Died in prison', 'Known as the "Gaffney Strangler"');
INSERT INTO SKD VALUES ('Martin, Rhonda Belle', 1926, 1951, 1, '6', 'Executed 1957', 'Alabama woman who poisoned family members');
INSERT INTO SKD VALUES ('Mason, David', 1980, 1982, 5, '6', 'Executed 1993', 'Killed four elderly neighbours in 1980 and his cellmate in 1982 while imprisoned on lesser charges; suspected of shooting dead his boyfriend');
INSERT INTO SKD VALUES ('Mason, Samuel', 1797, 1803, 20, '20+', 'Killed/Died from injuries received during a shoot-out', 'River pirate associated with the Harpe brothers and other outlaws');
INSERT INTO SKD VALUES ('Matthew, Jesse', 2009, 2014, 2, '7', 'Sentenced to life imprisonment', 'Believed to have raped, murdered, and sexually assaulted multiple women in Virginia from 2002 to 2014');
INSERT INTO SKD VALUES ('Maust, David Edward', 1974, 2003, 5, '5', 'Committed suicide in prison', 'Convicted of killing five teenage boys; one in Germany in 1974, another in 1981, and three he buried in his basement');
INSERT INTO SKD VALUES ('Mayrand, Edward', 1983, 1994, 3, '3', 'Died in prison', 'Strangled to death three women around New England');
INSERT INTO SKD VALUES ('McCarthy, Kimberly', 1997, 1998, 1, '3', 'Executed 2013', 'Crack addict who murdered a neighbour; suspect in two similar murders');
INSERT INTO SKD VALUES ('McDuff, Kenneth', 1966, 1992, 9, '14+', 'Executed 1998', 'Known as the "Broomstick Killer"; death sentence for 1966 triple-murder commuted; killed three days after 1989 parole');
INSERT INTO SKD VALUES ('McFadden, Jerry Walter', 1973, 1986, 4, '4', 'Executed 1999', 'Known as "The Animal"');
INSERT INTO SKD VALUES ('McKnight, Anthony', 1985, 1986, 5, '5', 'Died in prison', 'Known as "The East Bay Slayer"; rapist who killed young girls and women in Oakland');
INSERT INTO SKD VALUES ('Meirhofer, David', 1967, 1974, 4, '4', 'Committed suicide', 'First serial killer to be apprehended via usage of offender profiling');
INSERT INTO SKD VALUES ('Melanson, Roy', 1974, 1988, 3, '5+', 'Sentenced to life imprisonment', 'Drifter connected to the rape-murders of at least three women in three states');
INSERT INTO SKD VALUES ('Metheny, Joe', 1976, 1996, 5, '10', 'Died in prison', '');
INSERT INTO SKD VALUES ('Mikhel, Iouri Gherman', 2001, 2002, 5, '5', 'Sentenced to death', 'Murdered five people in California with accomplice Jurijus Kadamovas.');
INSERT INTO SKD VALUES ('Moore, Henry Lee', 1911, 1912, 2, '25', 'Released 1956', 'Suspect in the Villisca axe murders; sentenced to life imprisonment for killing his mother and grandmother with an axe, later commuted and released from prison');
INSERT INTO SKD VALUES ('Moore, Manuel', 1973, 1974, 15, '73+', 'Sentenced to life imprisonment', 'Part of the "Death Angels" cult responsible for the Zebra murders');
INSERT INTO SKD VALUES ('Morin, Stephen', 1969, 1981, 4, '48', 'Executed 1985', 'Suspected in over 30 unsolved violent crimes across the country');
INSERT INTO SKD VALUES ('Morris, Dontae', 2010, 2011, 5, '7', 'Sentenced to life imprisonment; later changed to the death sentence', 'Murdered three men in drug-related scandals, as well as two policemen who tried to arrest him; also suspected in the deaths of two other men.');
INSERT INTO SKD VALUES ('Mors, Frederick', 1914, 1915, 8, '8', 'Unknown', 'Committed to Hudson River State Hospital; escaped in May 1916');
INSERT INTO SKD VALUES ('Moseley, Winston', 1963, 1964, 3, '3', 'Died in prison', 'Necrophile who sexually assaulted and murdered three women, including Kitty Genovese');
INSERT INTO SKD VALUES ('Mosley, Eddie', 1973, 1987, 8, '16+', 'Died in prison', 'Raped and murdered numerous young girls and women in and around Fort Lauderdale, Florida');
INSERT INTO SKD VALUES ('Muhammad, John Allen', 2002, 2003, 7, '17', 'Executed 2009', 'With accomplice Lee Boyd Malvo, perpetrated the D.C. sniper attacks');
INSERT INTO SKD VALUES ('Mullin, Herbert', 1972, 1973, 11, '13', 'Sentenced to life imprisonment', 'Eligible for parole in 2021');
INSERT INTO SKD VALUES ('Murphy, Donald', 1979, 1980, 2, '6+', 'Sentenced to 60 years imprisonment', 'Murdered between two and at least six prostitutes in Detroit; another man was wrongfully suspected of three murders');
INSERT INTO SKD VALUES ('Nance, Wayne', 1974, 1986, 0, '5+', 'Killed by intended victim', 'Known as the "Missoula Mauler"');
INSERT INTO SKD VALUES ('Nardello, Antonio', 1884, 1885, 3, '3', 'Executed 1886', 'Italian laborer who robbed and murdered other laborers in Maryland and Washington, D.C.');
INSERT INTO SKD VALUES ('Naso, Joseph', 1977, 1994, 6, '10', 'Sentenced to death', 'Also a suspect in the Alphabet murders case');
INSERT INTO SKD VALUES ('Neelley, Alvin', 1982, 1983, 2, '2', 'Died in prison', 'Committed murders with wife Judith Neelley');
INSERT INTO SKD VALUES ('Neelley, Judith', 1982, 1983, 2, '2', 'Death sentence commuted to life imprisonment', 'Committed murders with husband Alvin Neelley');
INSERT INTO SKD VALUES ('Nelson, Earle', 1926, 1927, 22, '22+', 'Executed 1928', 'Known as the "Gorilla Man"');
INSERT INTO SKD VALUES ('Newman, Allan Patterson', 1991, 1992, 4, '4', 'Died in prison', 'Murdered carjacking victims during a three-state crime spree');
INSERT INTO SKD VALUES ('Ng, Charles', 1983, 1985, 11, '25', 'Sentenced to death', 'Along with accomplice Leonard Lake, they are also known as the "Operation Miranda Killers"');
INSERT INTO SKD VALUES ('Nixon, Robert', 1937, 1938, 3, '5', 'Executed 1939', 'Nixon served, in part, as the basis of the character of Bigger Thomas in Richard Wrights 1940 social protest novel Native Son');
INSERT INTO SKD VALUES ('Noe, Marie', 1949, 1968, 8, '8', 'Sentenced to 20 years probation in 1998', 'Murdered eight of her children; two others died of natural causes');
INSERT INTO SKD VALUES ('Norris, Roy', 1979, 1980, 5, '5', 'Died in prison', 'With accomplice Lawrence Bittaker known as "Tool Box Killers"');
INSERT INTO SKD VALUES ('Northcott, Gordon Stewart', 1926, 1928, 3, '20', 'Executed 1930', 'His mother, Sarah Louise Northcott, was implicated as an accomplice');
INSERT INTO SKD VALUES ('Ocampo, Itzcoatl', 2011, 2012, 6, '6', 'Committed suicide before trial', 'Former marine suspected of killing six people around Orange County, California');
INSERT INTO SKD VALUES ('ODell, Diane', 1982, 1985, 3, '4', 'Sentenced to life imprisonment', 'Murdered her illegitimate infants');
INSERT INTO SKD VALUES ('Pace, Lyndon Fitzgerald', 1988, 1989, 4, '5', 'Sentenced to death', 'In 1990, he robbed the apartment of Coretta Scott King');
INSERT INTO SKD VALUES ('Panzram, Carl', 1920, 1929, 5, '22', 'Executed 1930', 'Murderer, rapist, and arsonist; convicted of two murders, but confessed to 19 others');
INSERT INTO SKD VALUES ('Pardo, Manuel', 1986, 1987, 9, '9', 'Executed 2012', 'Former police officer');
INSERT INTO SKD VALUES ('Parker, Gerald', 1978, 1978, 6, '6', 'Sentenced to death', 'Known as the "Bedroom Basher"');
INSERT INTO SKD VALUES ('Peete, Louise', 1913, 1944, 3, '3+', 'Executed 1947', 'Convicted of murdering a man and woman decades apart; four other acquaintances died suspiciously and four husbands committed suicide');
INSERT INTO SKD VALUES ('Pennell, Steven Brian', 1987, 1988, 2, '5', 'Executed 1992', 'Known as the "Route 40 Killer"');
INSERT INTO SKD VALUES ('Peterson, Christopher', 1990, 1991, 4, '7', 'Incarcerated 120 years', 'Also known as the "Shotgun Killer"');
INSERT INTO SKD VALUES ('Pierce, William', 1970, 1971, 9, '9+', 'Sentenced to life imprisonment', 'One of his victims was the daughter of a South Carolina state senator');
INSERT INTO SKD VALUES ('Piper, Thomas W.', 1873, 1875, 2, '2+', 'Executed 1876', 'Known as the "Boston Belfry Murderer"');
INSERT INTO SKD VALUES ('Player, Michael', 1986, 1987, 10, '10', 'Committed suicide to avoid apprehension', 'Known as the "Skid Row Slayer"');
INSERT INTO SKD VALUES ('Pomeroy, Jesse', 1874, 1875, 2, '9', 'Died in prison', 'Known as "The Boy Torturer"');
INSERT INTO SKD VALUES ('Powers, Harry', 1931, 1932, 5, '5+', 'Executed 1932', 'Known as "The West Virginia Bluebeard"');
INSERT INTO SKD VALUES ('Presley, Aeman', 2014, 2015, 4, '4', 'Sentenced to life imprisonment', 'Shot and killed people in DeKalb and Fulton Counties, Georgia during robberies');
INSERT INTO SKD VALUES ('Price, Craig', 1987, 1989, 4, '4', 'Incarcerated', 'Convicted as a minor; given an additional 10–25 year sentence for assaulting a corrections officer in prison');
INSERT INTO SKD VALUES ('Priest, Martin', 1980, 1985, 2, '5', 'Sentenced to life imprisonment', 'Convicted of murdering a young girl and one man in both Missouri and Kansas; acquitted, but still main suspect, in three other deaths');
INSERT INTO SKD VALUES ('Prince Jr., Cleophus', 1990, 1991, 6, '6', 'Sentenced to death', 'Also known as the "Clairemont Killer"');
INSERT INTO SKD VALUES ('Pruett, Marion Albert', 1981, 1982, 5, '5', 'Executed 1999', 'Committed his crimes while in the United States Federal Witness Protection Program');
INSERT INTO SKD VALUES ('Pruitt, Pleasant', 1888, 1902, 3, '3', 'Committed suicide to avoid apprehension', 'Murdered his three wives in Indiana');
INSERT INTO SKD VALUES ('Puente, Dorothea', 1982, 1988, 9, '15', 'Died in prison', 'Convicted of three killings; suspected of six others');
INSERT INTO SKD VALUES ('Rachals, Terri', 1980, 1986, 6, '9', 'Released 2003', 'Former nurse who murdered patients at Phoebe Putney Memorial Hospital in Albany, Georgia with potassium chloride');
INSERT INTO SKD VALUES ('Rader, Dennis', 1974, 1991, 10, '10', 'Incarcerated–life imprisonment', 'Also known as the "BTK Killer"');
INSERT INTO SKD VALUES ('Ramirez, Richard', 1984, 1985, 14, '14', 'Died in prison awaiting execution', 'Known as the "Night Stalker"');
INSERT INTO SKD VALUES ('Rasmussen, Terry Peder', 1978, 2002, 6, '6+', 'Died in prison', 'Known as the "Chameleon Killer"; main suspect in the Bear Brook murders, as well as other murders');
INSERT INTO SKD VALUES ('Ray, David Parker', 1950, 1999, 0, '60', 'Died in prison', 'Convicted of kidnapping and torture in 2001, but never convicted of murder');
INSERT INTO SKD VALUES ('Reed, Todd Alan', 1999, 2000, 3, '5', 'Sentenced to life imprisonment', 'Known as "The Forest Park Killer"');
INSERT INTO SKD VALUES ('Rees, Melvin', 1957, 1959, 5, '9+', 'Died in prison', 'Known as the "Sex Beast"');
INSERT INTO SKD VALUES ('Reeves, Jack', 1967, 1994, 4, '4', 'Sentenced to 99 years imprisonment', 'Killed his three wives after they planned to leave him; also killed a man while stationed in Italy');
INSERT INTO SKD VALUES ('Reid, Paul Dennis', 1997, 1998, 7, '7', 'Died in prison awaiting execution', 'Known as the "Fast Food Killer"');
INSERT INTO SKD VALUES ('Rembert, Robert', 1997, 2015, 5, '5+', 'Sentenced to life imprisonment', 'Truck driver who killed people across Ohio');
INSERT INTO SKD VALUES ('Reséndiz, Ángel Maturino', 1986, 1999, 10, '16', 'Executed 2006', 'Also known as "The Railroad/Railway/Railcar Killer"');
INSERT INTO SKD VALUES ('Rhoades, Robert Ben', 1975, 1990, 3, '50+', 'Sentenced to life imprisonment', 'Known as the "Truck Stop Killer"');
INSERT INTO SKD VALUES ('Richards, Stephen Dee', 1876, 1878, 9, '9', 'Executed 1879', 'Known as the "Nebraska Fiend"');
INSERT INTO SKD VALUES ('Ridgway, Gary', 1982, 1998, 49, '90+', 'Sentenced to life imprisonment', 'Known as the "Green River Killer"');
INSERT INTO SKD VALUES ('Rifkin, Joel', 1989, 1993, 9, '17+', 'Incarcerated for 203 years to life', 'Mostly preyed on sex workers in New York City and Long Island');
INSERT INTO SKD VALUES ('Rissell, Montie', 1976, 1977, 5, '5', 'Sentenced to life imprisonment', 'Raped and murdered women in Alexandria, Virginia');
INSERT INTO SKD VALUES ('Ritchie, James Dale', 2016, 2017, 5, '5+', 'Killed by police during apprehension', 'Known as the "Anchorage Serial Killer"');
INSERT INTO SKD VALUES ('Rivera, Reinaldo', 1999, 2000, 4, '4', 'Sentenced to death', 'Abducted, raped and killed women in the Augusta metropolitan area');
INSERT INTO SKD VALUES ('Robinson, Alonzo', 1926, 1934, 2, '6', 'Executed 1935', 'Grave robber and cannibal convicted of a double murder; also suspected of murdering four women');
INSERT INTO SKD VALUES ('Robinson, Harvey Miguel', 1992, 1993, 3, '3', 'Sentenced to death', 'Teenager who stalked, raped and killed');
INSERT INTO SKD VALUES ('Robinson, John Edward', 1984, 1999, 8, '8+', 'Sentenced to death', 'Sometimes referred to as "The Internets first serial killer"');
INSERT INTO SKD VALUES ('Robinson, Sarah Jane', 1881, 1886, 8, '11', 'Died in prison', 'Known as the "Boston Borgia"');
INSERT INTO SKD VALUES ('Rodriguez, Robert Neal', 1984, 1992, 3, '3', 'Committed suicide while a fugitive', 'Former police officer');
INSERT INTO SKD VALUES ('Rogers, Dayton Leroy', 1983, 1987, 7, '8+', 'Sentenced to death', 'Known as the "Molalla Forest Killer"');
INSERT INTO SKD VALUES ('Rogers, Glen Edward', 1993, 1995, 4, '5', 'Sentenced to death', 'Death sentence currently under appeal');
INSERT INTO SKD VALUES ('Rolling, Danny', 1989, 1990, 8, '8', 'Executed 2006', 'Pleaded guilty to murdering five students in Gainesville, Florida');
INSERT INTO SKD VALUES ('Ross, Michael Bruce', 1981, 1984, 8, '8+', 'Executed 2005', 'Known as the "Roadside Strangler"');
INSERT INTO SKD VALUES ('Rozier, Robert', 1981, 1986, 4, '7', 'Serving 25 years to life on a conviction for check kiting under a third strike law', 'Former NFL player; sentenced to 22 years for murder after agreeing to testify against Yahweh ben Yahwehs organization');
INSERT INTO SKD VALUES ('Rulloff, Edward H.', 1844, 1870, 3, '5', 'Executed 1871', 'Known as the "Genius Killer"');
INSERT INTO SKD VALUES ('Runge, Paul', 1995, 1997, 7, '8+', 'Sentenced to death; commuted to life imprisonment', 'Sexually assaulted and murdered women and one girl in Cook and DuPage counties in Illinois');
INSERT INTO SKD VALUES ('Russell, George Waterfield', 1990, 1991, 3, '3', 'Sentenced to life imprisonment', 'Known as "The Charmer"; raped and murdered women in Seatte suburbs, mutilating and having sex with the corpses afterwards');
INSERT INTO SKD VALUES ('Rutterschmidt, Olga', 1999, 2005, 2, '2', 'Sentenced to life imprisonment without parole', 'Killed vagrants with her partner-in-crime, Helen Golay');
INSERT INTO SKD VALUES ('Saenz, Kimberly Clark', 2008, 2009, 5, '10+', 'Sentenced to life imprisonment', 'Killed five patients by injecting bleach into their dialysis lines');
INSERT INTO SKD VALUES ('Saldivar, Efren', 1988, 1998, 6, '50+', 'Sentenced to life imprisonment', '');
INSERT INTO SKD VALUES ('Sanchez, Altemio', 1990, 2006, 3, '3+', 'Incarcerated, 75 years to life', 'Known as the "Bike Path Rapist"; responsible for three murders and numerous rapes spanning a 25-year period in Buffalo, New York');
INSERT INTO SKD VALUES ('Santo, Anthony', 1908, 1909, 3, '3', 'Supposedly died while incarcerated at Taunton Lunatic Asylum', 'Juvenile who murdered two cousins and a girl during "mad spells"');
INSERT INTO SKD VALUES ('Schaefer, Gerard John', 1969, 1973, 2, '34', 'Murdered in prison by fellow inmate Vincent Rivera', 'Imprisoned in 1973 for the murders of two women while he was a sheriffs deputy in Martin County, Florida');
INSERT INTO SKD VALUES ('Schmid, Charles', 1964, 1965, 3, '4', 'Murdered in prison by unknown assailants', 'Also known as "The Pied Piper of Tucson"');
INSERT INTO SKD VALUES ('Schmidt, Helmuth', 1913, 1917, 1, '4+', 'Committed suicide in prison', 'Known as the "American Bluebeard"');
INSERT INTO SKD VALUES ('Seda, Heriberto', 1990, 1993, 3, '3', 'Sentenced to life imprisonment', 'New York City copycat of the Zodiac Killer; selected his victims based on their astrological signs');
INSERT INTO SKD VALUES ('Segundo, Juan', 1986, 1995, 4, '7+', 'Sentenced to death', '');
INSERT INTO SKD VALUES ('Sellers, Sean', 1985, 1986, 3, '3', 'Executed 1999', 'One of 22 persons in the United States since the reinstatement of the death penalty in 1976 to be executed for a crime committed while under the age of 18, and the lone to have been executed for crime committed under the age of 17');
INSERT INTO SKD VALUES ('Sells, Tommy Lynn', 1980, 1999, 6, '22+', 'Executed 2014', 'Confessed to murdering dozens of people, possibly in excess of 70, only six are confirmed');
INSERT INTO SKD VALUES ('Selz, Ralph Jerome Von Braun', 1930, 1935, 1, '5', 'Unknown', 'Known as "The Laughing Killer"');
INSERT INTO SKD VALUES ('Severance, Charles', 2003, 2014, 3, '3', 'Sentenced to life imprisonment', 'Murdered elderly residents in Alexandria out of hatred for the rich');
INSERT INTO SKD VALUES ('Shaw, Sebastian', 1991, 1992, 3, '13', 'Sentenced to life imprisonment', 'Murdered victims selected at random in Portland, Oregon; confessed to additional murders, including one in California');
INSERT INTO SKD VALUES ('Shawcross, Arthur', 1972, 1989, 12, '14', 'Died in prison', 'Also known as the "Genesee River Killer"');
INSERT INTO SKD VALUES ('Sherman, Lydia', 1863, 1877, 12, '12', 'Died in prison', 'Known as the "Derby Poisoner"');
INSERT INTO SKD VALUES ('Shermantine, Wesley', 1984, 1999, 4, '19', 'Sentenced to death', 'Along with accompliace Loren Herzog known as the "Speed Freak Killers"');
INSERT INTO SKD VALUES ('Shore, Anthony Allen', 1986, 1995, 4, '4+', 'Executed 2018', 'Also known as the "Tourniquet Killer"');
INSERT INTO SKD VALUES ('Shulman, Robert', 1991, 1996, 5, '5', 'Died in prison', 'Preyed on sex workers in New York');
INSERT INTO SKD VALUES ('Siebert, Daniel Lee', 1979, 1986, 10, '13', 'Died in prison', 'Killed nine people across America in three months');
INSERT INTO SKD VALUES ('Silveria Jr., Robert Joseph', 1981, 1996, 9, '14+', 'Sentenced to life imprisonment', 'Known as the "Boxcar Killer", alleged member of Freight Train Riders of America');
INSERT INTO SKD VALUES ('Simon, J.C.X.', 1973, 1974, 15, '73+', 'Died in prison', 'Part of the "Death Angels" cult responsible for the Zebra murders');
INSERT INTO SKD VALUES ('Sinclair, Charles T.', 1980, 1990, 13, '13+', 'Died in prison', 'Known as the "Coin Shop Killer"');
INSERT INTO SKD VALUES ('Smith, Lemuel', 1958, 1981, 5, '6', 'Sentenced to death; commuted to life', 'First convict to kill an on-duty female corrections officer');
INSERT INTO SKD VALUES ('Smith, Mark Alan', 1969, 1970, 4, '12+', 'Sentenced to life imprisonment', 'Convicted of killing at least four women in Illinois and Arkansas; claimed in his book to have murdered eight women while stationed in Germany');
INSERT INTO SKD VALUES ('Solomon Jr., Morris', 1986, 1987, 6, '7', 'Sentenced to death', 'Known as the "Sacramento Slayer"');
INSERT INTO SKD VALUES ('Southard, Lyda', 1915, 1920, 6, '6', 'Released in 1941', 'Known as "Flypaper Lyda"; serial poisoner who killed four husbands, a young daughter and a brother-in-law');
INSERT INTO SKD VALUES ('Sowell, Anthony', 2007, 2009, 11, '11', 'Sentenced to death', 'Also known as "The Cleveland Strangler" and "The Imperial Avenue Murderer"');
INSERT INTO SKD VALUES ('Spencer, Timothy Wilson', 1984, 1988, 5, '5', 'Executed 1994', 'Known as the "Southside Strangler"');
INSERT INTO SKD VALUES ('Spillman, Jack Owen', 1994, 1995, 3, '3', 'Sentenced to life imprisonment', 'Known as the "Werewolf Butcher"');
INSERT INTO SKD VALUES ('Spreitzer, Edward', 1981, 1982, 18, '18', 'Sentenced to life imprisonment', 'Member of the satanic cult and organized crime group known as "The Ripper Crew" or "The Chicago Rippers"');
INSERT INTO SKD VALUES ('Stafford, Roger Dale', 1974, 1978, 9, '34', 'Executed 1995', 'His wife implicated in 34 different murders in seven different states');
INSERT INTO SKD VALUES ('Stano, Gerald', 1969, 1980, 22, '41+', 'Executed 1998', 'Guilt has been questioned');
INSERT INTO SKD VALUES ('Stayner, Cary', 1999, 2000, 4, '4', 'Sentenced to death', 'Brother of kidnap victim Steven Stayner');
INSERT INTO SKD VALUES ('Stephani, Paul Michael', 1980, 1982, 3, '3', 'Died in prison', 'Known as the "Weepy-Voiced Killer" due to a series of telephone calls he made to police, anonymously reporting his crimes in a remorseful and high-pitched voice. Active in the Minneapolis–Saint Paul area');
INSERT INTO SKD VALUES ('Stickles, Martin', 1899, 1900, 3, '3', 'Executed 1901', 'Known as "The Kelso Killer"; murdered three people during robberies in Cowlitz County, Washington');
INSERT INTO SKD VALUES ('Stokes, Winford', 1969, 1978, 3, '3', 'Executed 1990', 'Career criminal and prison escapee who murdered people in St. Louis');
INSERT INTO SKD VALUES ('Strong, Preston', 2005, 2007, 7, '7', 'Sentenced to death', 'Was sentenced to life in prison for the 2007 murder of a doctor during a home robbery. Was later found guilty of the murder of a family of six during a robbery from 2005.');
INSERT INTO SKD VALUES ('Suff, William', 1974, 1992, 12, '22', 'Sentenced to death', 'Known as "The Riverside Prostitute Killer"');
INSERT INTO SKD VALUES ('Sumpter, Michael', 1969, 1973, 3, '3', 'Died in 2001', '');
INSERT INTO SKD VALUES ('Swango, Michael', 1981, 1997, 4, '60', 'Sentenced to life imprisonment', 'Physician and surgeon');
INSERT INTO SKD VALUES ('Swann, James', 1993, 1994, 4, '4', 'Found not guilty by reason of insanity and confined to Saint Elizabeths Hospital', 'Known as the "Shotgun Stalker"');
INSERT INTO SKD VALUES ('Taborsky, Joseph "Mad Dog"', 1950, 1957, 7, '7', 'Executed 1960', '');
INSERT INTO SKD VALUES ('Tann, Georgia', 1924, 1950, 19, '19+', 'Died of uterine cancer before she could be arrested', 'Child trafficker who sold kidnapped children to the black market');
INSERT INTO SKD VALUES ('Terry, Charles E.', 1951, 1963, 1, '4+', 'Died in prison', 'Suspected of committing some of the Boston Strangler murders');
INSERT INTO SKD VALUES ('Tholmer, Brandon', 1981, 1983, 12, '34', 'Sentenced to life imprisonment', 'Known as the "West Side Rapist"; preyed on elderly women in Westside, Los Angeles County');
INSERT INTO SKD VALUES ('Thomas Jr., John Floyd', 1972, 1986, 7, '15+', 'Sentenced to life imprisonment', 'Known as "The Southland Strangler" and "The Westside Rapist"');
INSERT INTO SKD VALUES ('Thompson, William Paul', 1983, 1984, 3, '6', 'Executed 1989', '');
INSERT INTO SKD VALUES ('Tinning, Marybeth', 1972, 1985, 2, '9', 'Sentenced to 20 years to life', '');
INSERT INTO SKD VALUES ('Toole, Ottis', 1976, 1983, 6, '6+', 'Died in prison. Claimed to have murdered Adam Walsh', 'Accomplice of Henry Lee Lucas');
INSERT INTO SKD VALUES ('Toppan, Jane', 1895, 1901, 12, '31+', 'Found not guilty by reason of insanity and committed for life to the Taunton State Hospital', 'Known as "Jolly Jane"; nurse who poisoned both patients and family members');
INSERT INTO SKD VALUES ('Travis, Maury', 2000, 2002, 2, '17+', 'Committed suicide awaiting trial', '');
INSERT INTO SKD VALUES ('Turner, Chester', 1987, 1998, 15, '16', 'Sentenced to death', 'Convicted of murdering ten women and a viable unborn baby in South Los Angeles');
INSERT INTO SKD VALUES ('Urdiales, Andrew', 1986, 1996, 8, '8', 'Committed suicide in prison', 'Murdered woman in Indiana, Illinois and California');
INSERT INTO SKD VALUES ('Valkenburgh, Elizabeth Van', 1833, 1845, 2, '2', 'Executed 1846', 'Self-confessed poisoner who killed her alcoholic husbands');
INSERT INTO SKD VALUES ('Vann, Darren Deon', 2013, 2014, 7, '7+', 'Sentenced to life imprisonment', 'Indiana murderer who killed seven women; five of which were found in abandoned structures in the city of Gary');
INSERT INTO SKD VALUES ('Vermilya, Louise', 1893, 1911, 9, '9', 'Died in 1913', 'Charges dismissed');
INSERT INTO SKD VALUES ('Walker, Anthony Guy', 1975, 1986, 6, '6+', 'Sentenced to life imprisonment', 'Career criminal who murdered mainly across Lenawee County, Michigan');
INSERT INTO SKD VALUES ('Wallace, Henry Louis', 1990, 1994, 11, '11', 'Sentenced to death', 'Known as "The Taco Bell Strangler"');
INSERT INTO SKD VALUES ('Walton, Edward', 1896, 1908, 5, '5', 'Executed 1908', 'Confessed to murdering five people across five states');
INSERT INTO SKD VALUES ('Ward, Ronald James', 2000, 2001, 4, '4+', 'Died in prison', 'Murdered at least three women and one man in three states, in the span of four months');
INSERT INTO SKD VALUES ('Wardrip, Faryion', 1984, 1986, 5, '5', 'Sentenced to death', 'Death sentence currently under appeal');
INSERT INTO SKD VALUES ('Warren, Edward Delon', 1976, 1979, 3, '3', 'Died in prison', 'Murdered a couple in Brookings, Oregon; later linked via DNA to an unsolved murder in Portland');
INSERT INTO SKD VALUES ('Watson, Alexander Wayne', 1986, 1994, 4, '4', 'Sentenced to life imprisonment', 'Raped, stabbed and strangled women in two Maryland counties');
INSERT INTO SKD VALUES ('Watts, Carl Eugene', 1974, 1982, 22, '100', 'Died in prison', 'Known as the "Sunday Morning Slasher"');
INSERT INTO SKD VALUES ('Werner, Karl F.', 1969, 1971, 3, '3', 'Sentenced to life imprisonment', 'Murdered teenage girls in Santa Clara County, California');
INSERT INTO SKD VALUES ('White, Nathaniel', 1991, 1992, 6, '6', 'Sentenced to 150 years to life in prison', 'Confessed to beating and stabbing six women to death while on parole');
INSERT INTO SKD VALUES ('Whiteling, Sarah', 1888, 1889, 3, '3', 'Executed 1889', 'Known as the "Wholesale Poisoner"');
INSERT INTO SKD VALUES ('Whitten, Hattie', 1900, 1902, 3, '3', 'Committed suicide before trial', 'Maine woman who poisoned her husband and two children');
INSERT INTO SKD VALUES ('Wilder, Christopher', 1984, 1985, 8, '15', 'Killed by police during apprehension', 'Also known as the "Beauty Queen Killer"');
INSERT INTO SKD VALUES ('Williams, Scott', 1997, 2006, 3, '3', 'Sentenced to life imprisonment', '');
INSERT INTO SKD VALUES ('Williams, Wayne', 1979, 1981, 2, '23', 'Sentenced to life imprisonment', 'Has maintained his innocence from the beginning and conviction is considered controversial');
INSERT INTO SKD VALUES ('Williamson, Thomas Andrew', 1868, 1890, 4, '4', 'Executed 1891', 'Murdered four people in Illinois and Missouri, including his wife');
INSERT INTO SKD VALUES ('Wimberly, Anthony', 1984, 1985, 3, '3', 'Sentenced to life imprisonment', 'Murdered three women in Oakland during a crime spree');
INSERT INTO SKD VALUES ('Winters, Shirley', 1980, 2006, 2, '7', 'Sentenced to eight to 25 years', '');
INSERT INTO SKD VALUES ('Wise, Martha', 1924, 1925, 3, '3', 'Died in prison', 'Poisoned 17 members of her own family');
INSERT INTO SKD VALUES ('Wood, Cathy', 1987, 1988, 5, '6', 'Incarcerated 20–40 years', 'Eligible for parole since 2005');
INSERT INTO SKD VALUES ('Wood, Isaac L.', 1855, 1856, 3, '3', 'Executed 1858', 'Poisoned his wife, brother and sister-in-law for monetary purposes');
INSERT INTO SKD VALUES ('Woodfield, Randall', 1979, 1981, 18, '44', 'Sentenced to life imprisonment plus 165 years', 'Known as "The I-5 Killer" and "The I-5 Bandit"');
INSERT INTO SKD VALUES ('Wright, Douglas', 1969, 1991, 5, '5+', 'Executed 1996', 'First criminal executed by lethal injection in Oregon');
INSERT INTO SKD VALUES ('Wuornos, Aileen', 1989, 1990, 7, '7', 'Executed 2002', 'Also known as the "Damsel of Death"; shot seven men to death in Florida between 1989 and 1990');
INSERT INTO SKD VALUES ('Yates, Robert Lee', 1975, 1998, 13, '18+', 'Sentenced to death, commuted to life imprisonment', '');
INSERT INTO SKD VALUES ('Zarinsky, Robert', 1958, 1974, 2, '10', 'Died in prison', '');
INSERT INTO SKD VALUES ('Alphabet murders', 1971, 1973, 3, '3', 'NY', 'Also known as the "Double Initial Murders"; murders of three young girls in the Rochester, New York area in the early 1970s');
INSERT INTO SKD VALUES ('Ann Arbor Hospital Murders', 1975, 1976, 10, '10', 'MI', 'Poisonings of 10 patients at the Veterans Administration Hospital in 1975. Two nurses, Filipina Narciso and Leonora Perez, were convicted but a new trial was ordered because of prosecutorial misconduct. The prosecution chose to drop the charges rather than retry.');
INSERT INTO SKD VALUES ('Atlanta Ripper', 1911, 1912, 15, '15–21', 'GA', 'Mystery murderer(s) of 15 Atlanta women in 1911');
INSERT INTO SKD VALUES ('Axeman of New Orleans', 1918, 1919, 6, '6', 'LA', 'Responsible for the deaths of six or seven people in New Orleans and the surrounding areas from 1918–1919');
INSERT INTO SKD VALUES ('Boston Strangler', 1962, 1964, 13, '13', 'MA', '1960s deaths of 13 women (five young, eight older), mostly with their own stockings as ligature. Albert DeSalvo confessed to the murders, but was never indicted; DNA evidence tested in 2013 suggested his guilt in one of the cases');
INSERT INTO SKD VALUES ('Charlie Chop-off', 1972, 1974, 4, '4', 'NY', 'Murders of five boys in Manhattan in 1972 and 1973. A mental patient confessed to one slashing death. Four stabbings also involving mutilation remain unsolved');
INSERT INTO SKD VALUES ('Chicago Strangler', 2001, 2018, 55, '75', 'IL', 'Raped and strangled predominantly African-American prostitutes and other vulnerable women in Chicago; could possibly be multiple serial killers');
INSERT INTO SKD VALUES ('Cincinnati Strangler', 1965, 1966, 7, '7', 'OH', 'Raped and strangled seven mostly elderly women in Cincinnati, Ohio between 1965 and 1966; Cab driver Posteal Laskey, Jr. is commonly believed to be culprit');
INSERT INTO SKD VALUES ('Cleveland Torso Murderer', 1934, 1935, 13, '40+', 'OH', 'Also known as the "Mad Butcher of Kingsbury Run"; responsible for 12–13 murders in the Cleveland, Ohio area in the 1930s');
INSERT INTO SKD VALUES ('Colonial Parkway Killer', 1986, 1989, 8, '8', 'VA', 'Believed to have murdered at least eight people in Virginia between 1986 and 1989; left three couples dead and one couple missing and presumed dead');
INSERT INTO SKD VALUES ('Connecticut River Valley Killer', 1978, 1987, 7, '7+', 'MA, NH, VT', 'Stabbed at least six women to death in New England in the 1980s, severely injured one');
INSERT INTO SKD VALUES ('Cumminsville murders', 1904, 1910, 5, '5', 'OH', 'Series of brutal murders and mutilations of women in the Cincinnati neighborhood of South Cumminsville');
INSERT INTO SKD VALUES ('Dayton Strangler', 1900, 1909, 6, '6', 'OH', 'Murdered five women and one man in Dayton, Ohio in the early 20th-century; one man was wrongfully convicted for the murders');
INSERT INTO SKD VALUES ('Daytona Beach killer', 2005, 2016, 4, '7+', 'FL', 'Murdered four, possibly five, women in Daytona Beach, Florida between 2005 and 2007; Robert Hayes has been linked to three of the killings and is currently awaiting trial');
INSERT INTO SKD VALUES ('Denver Prostitute Killer', 1975, 1995, 17, '27', 'CO', 'Abducted, raped and strangled young girls and women around Denver and its various suburbs');
INSERT INTO SKD VALUES ('Denver Strangler', 1894, 1903, 3, '5', 'CO', 'Strangled three prostitutes in Denver in 10 weeks; also thought to be responsible in two more murders');
INSERT INTO SKD VALUES ('Detroit East Side Killer', 2018, 2019, 4, '4+', 'MI', 'Raped and murdered prostitutes in abandoned houses, posing them in a humiliating manner post-mortem; Deangelo Martin has been charged with the murders, and his trial is ongoing');
INSERT INTO SKD VALUES ('The Doodler', 1974, 1975, 14, '14', 'CA', 'Sketched then stabbed to death 14 gay men in San Francisco, California in the 1970s');
INSERT INTO SKD VALUES ('Dr. No', 1981, 2004, 9, '9+', 'OH, IL, NY, PA', 'Suspected of raping and strangling prostitutes alongside the Interstate 71; his first suspected victim is Marcia King, who was identified in 2018. Samuel Legg III, a trucker, has been arrested and charged but this far (as of 2020) is incompetent to stand trial. He is receiving psychiatric treatment while they try to restore competency.');
INSERT INTO SKD VALUES ('Eastbound Strangler', 2006, 2007, 4, '4', 'NJ', 'Murdered four women near Atlantic City, New Jersey in 2006.');
INSERT INTO SKD VALUES ('Edgecombe County Serial Killer', 2000, 2010, 9, '10', 'NC', 'Murders of nine women and disappearance of another since 2005 around Rocky Mount, North Carolina. Antwan Pittman has been convicted in one case');
INSERT INTO SKD VALUES ('Flat-Tire murders', 1975, 1976, 5, '5+', 'FL', 'Killed five women in 1975');
INSERT INTO SKD VALUES ('Flint Serial Slasher', 2009, 2010, 5, '5', 'MI, OH, VA', 'Stabbing attacks against mostly small-framed African-American men, with the main area being Flint, Michigan; an Israeli national, Elias Abuelazam, has been convicted in one of the murders and remains the prime suspect in the other four');
INSERT INTO SKD VALUES ('Frankford Slasher', 1985, 1990, 8, '9', 'PA', 'Allegedly responsible for nine murders in the Frankford neighborhood of Philadelphia, Pennsylvania; Leonard Christopher was convicted of one murder; another murder was committed in same style while he was incarcerated; believed to still be at large');
INSERT INTO SKD VALUES ('Freeway Phantom', 1971, 1972, 6, '6', 'DC', 'Raped and strangled six young women and girls in Washington, D.C. in the early 1970s, dumping their bodies by freeways');
INSERT INTO SKD VALUES ('Gypsy Hill killings', 1976, 1977, 5, '5+', 'CA', 'Known as the "San Mateo slasher"; five unsolved killings, of young women in San Mateo County, California during early 1976; in 2014, the FBI named Rodney Halbower as a person of interest in the Gypsy Hill killings; as of 2018, he has been convicted in two of the murders');
INSERT INTO SKD VALUES ('Hog Trail Murders', 1993, 1996, 6, '12', 'FL', 'Mutilated bodies of young men found in Charlotte County, Florida; thought to be linked to Daniel Conahan, who was charged and convicted of one of the murders.');
INSERT INTO SKD VALUES ('Honolulu Strangler', 1985, 1986, 5, '5', 'HI', 'Raped and strangled five young women in Hawaii in 1985 and 1986');
INSERT INTO SKD VALUES ('I-45 Killer', 1980, 1981, 0, '4+', 'TX', 'Strangled four known victims in 1980 and sexually assaulted some. Three of the four women have never been identified.');
INSERT INTO SKD VALUES ('I-70 Killer', 1992, 1994, 6, '8', 'IN, MO, KS', 'Killed and robbed six store clerks around the Midwestern United States');
INSERT INTO SKD VALUES ('Jeff Davis 8', 2005, 2009, 8, '8', 'LA', 'The bodies of eight women were found in swamps and canals surrounding Jennings, Louisiana. Originally thought to be a serial killer, but multiple suspects may be involved');
INSERT INTO SKD VALUES ('Long Island serial killer', 1996, 2010, 10, '17', 'NY', 'Suspected of killing eight women, a man and a child since 1996 and dumping their bodies along remote beaches in Suffolk and Nassau County, New York. The killer has been referred to as the Gilgo Beach killer because of the location where the first bodies were found');
INSERT INTO SKD VALUES ('The Man from the Train', 1900, 1912, 0, '40+', 'USA', 'Probably one Paul Mueller. Killed whole families in their sleep, from the east coast to the west and many places between, arriving and departing by train. Existence (and probable but not proven identity) discovered over 100 years after the murders, by analysis of contemporary records, showing a markedly common modus operandi for many previously unconnected crimes.');
INSERT INTO SKD VALUES ('Maryvale serial shooter', 2015, 2016, 9, '9', 'AZ', 'Attacked at night from a car using a handgun, killing seven people and injuring two between August 2015 and July 2016 in Phoenix, Arizona; Aaron Saucedo was arrested for all murders in 2017 and is awaiting trial');
INSERT INTO SKD VALUES ('Michigan Murders', 1967, 1969, 1, '7', 'MI', 'Raped, stabbed, and strangled young women between the ages of 13 and 21 in the Washtenaw County area of Michigan. John Norman Collins was convicted of the last murder in the series and strongly suspected to be responsible for all seven murders attributed to the same perpetrator.');
INSERT INTO SKD VALUES ('New Bedford Highway Killer', 1988, 1989, 9, '11', 'MA', 'Murders of nine women and disappearance of two others between 1988 and 1989');
INSERT INTO SKD VALUES ('Oakland County Child Killer', 1976, 1977, 4, '4+', 'MI', 'Also known as the "Babysitter"; responsible for the murders of four or more children in Oakland County, Michigan in 1976 and 1977');
INSERT INTO SKD VALUES ('Phantom Killer', 1946, 1947, 5, '5', 'TX', 'Believed to have committed the Texarkana Moonlight Murders in Texas between February 23 and May 4, 1946');
INSERT INTO SKD VALUES ('Redhead murders', 1978, 1992, 8, '11', 'TN, AR, KY, MS, PA, WV', 'Series of unsolved homicides believed to have been committed by an unidentified serial killer in Tennessee, Arkansas, Kentucky, Mississippi, Pennsylvania and West Virginia, also known as "The Bible Belt Strangler"');
INSERT INTO SKD VALUES ('Santa Rosa Hitchhiker Murders', 1972, 1973, 7, '7+', 'CA', 'A series of at least seven unsolved homicides involving female hitchhikers that took place in Sonoma County and Santa Rosa of the North Bay area of California in 1972 and 1973');
INSERT INTO SKD VALUES ('Seminole Heights serial killer', 2017, 2018, 4, '4', 'FL', 'Shot and killed four people, seemingly at random, in the Seminole Heightsneighborhood of Tampa, Florida. On November 28, 2017, police arrested Howell Emanuel Donaldson III in connection with the killings. Donaldson is set for pre-trial hearing on August 20, 2020.');
INSERT INTO SKD VALUES ('Servant Girl Annihilator', 1884, 1885, 8, '8', 'TX', 'Also known as the "Austin Axe Murderer"; responsible for at least seven murders in Austin, Texas between 1884 and 1885');
INSERT INTO SKD VALUES ('Skid Row Stabber', 1978, 1979, 11, '11', 'CA', 'Murdered homeless men in Los Angeles Skid Row neighborhood; Bobby Joe Maxwell was falsely convicted of two of the murders and accused of the rest, and died while in a coma prior to being exonerated');
INSERT INTO SKD VALUES ('Smiley face murder theory', 1990, 2010, 0, '40+', 'USA', 'Theoretical serial killer(s) thought by some sources to have drowned college-aged young men across the northern part of the country since 1997; most experts suggest that the deaths were accidental');
INSERT INTO SKD VALUES ('Texas Killing Fields', 1970, 2010, 1, '30+', 'TX', 'Since the early 1970s, roughly 30 bodies have been extracted from the fields, mainly consisting of young girls. May have been the work of multiple killers. Convicted murderer Edward Harold Bell, 72 years old in November 2011, claimed in a letter to police in 1998 to have murdered 11 girls in Galveston County. Kevin Edison Smith was sentenced to life imprisonment for one of the murders in 2012.');
INSERT INTO SKD VALUES ('Tube Sock Killings', 1985, 1986, 4, '6', 'WA', 'Unsolved murders which occurred in the remote community of Mineral in Washington');
INSERT INTO SKD VALUES ('West Mesa murders', 2003, 2009, 11, '11+', 'NM', 'Remains of 11 women, who disappeared between 2003 and 2005, found buried in desert in Albuquerque, New Mexico in 2009 and attributed to a bone collector');
INSERT INTO SKD VALUES ('Zodiac Killer', 1968, 1974, 5, '37', 'CA, NV (possible)', 'Targeted young couples. Remains unsolved but open in the Californiajurisdictions the five certain Zodiac murders occurred. Potentially 37 total victims claimed but unverified.');
